// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmW1BCp2ezuY6QNFaQxQX9-AYcboiB9Hs',
    appId: '1:67193969716:web:d3a3904c74750ddb2fbe61',
    messagingSenderId: '67193969716',
    projectId: 'pharmacare-5face',
    authDomain: 'pharmacare-5face.firebaseapp.com',
    storageBucket: 'pharmacare-5face.firebasestorage.app',
    measurementId: 'G-7PZE2V7K0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPqKvFLQANZ53IMyUVX7z1m41KtA0x8lE',
    appId: '1:67193969716:android:b840c5e8d19b73cf2fbe61',
    messagingSenderId: '67193969716',
    projectId: 'pharmacare-5face',
    storageBucket: 'pharmacare-5face.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1F74Gglw9i5BNSxzLm26EKLuJebKIaHc',
    appId: '1:67193969716:ios:77a3d8722a3151e92fbe61',
    messagingSenderId: '67193969716',
    projectId: 'pharmacare-5face',
    storageBucket: 'pharmacare-5face.firebasestorage.app',
    iosBundleId: 'com.example.pharmacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1F74Gglw9i5BNSxzLm26EKLuJebKIaHc',
    appId: '1:67193969716:ios:77a3d8722a3151e92fbe61',
    messagingSenderId: '67193969716',
    projectId: 'pharmacare-5face',
    storageBucket: 'pharmacare-5face.firebasestorage.app',
    iosBundleId: 'com.example.pharmacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmW1BCp2ezuY6QNFaQxQX9-AYcboiB9Hs',
    appId: '1:67193969716:web:7d7ff03a3775f61c2fbe61',
    messagingSenderId: '67193969716',
    projectId: 'pharmacare-5face',
    authDomain: 'pharmacare-5face.firebaseapp.com',
    storageBucket: 'pharmacare-5face.firebasestorage.app',
    measurementId: 'G-9F5SPBST1F',
  );
}
