name: pharmacare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_auth_web: ^5.14.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.3.0
  js: ^0.7.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "image/Pharma.png"

flutter:
  uses-material-design: true
  assets:
    - image/
